### ISSUE TITLE
Did you read my README?

### ISSUE THREAD

**Issue by coderbot16** [Someone-Else-Was-Taken/Periodic-Table-Reforged#19]
I see you may be attempting a port of Iris.

Please read this section in full: https://github.com/IrisShaders/Iris#but-wheres-the-forge-version

How do you plan to address these issues? If you do not have a plan, then I ask that you do not port Iris because that will create a lot of problems for me and my support team in addition to damaging my mod's reputation.

You should see the corresponding version of that document for CaffeineMC as well: https://github.com/CaffeineMC/caffeine-meta/wiki/FAQ#where-are-the-forge-versions-of-your-mods

**Comment by viceversagames** [comment]
"Damaging your reputation," give me a break. This mod is awesome and Forge players want it. The fact that it is even getting ported means it's a good mod. 

 The Iris readme simply says it's possible but annoying on Forge. And that you don't want someone attempting a low effort port. I don't see how those are technical issues that need "addressing."

CaffeineMC seems to be opposed almost entirely because of personal problems with Forge staff. While that's entirely understandable, that's no reason to be against having a Forge port.

I don't understand the problem with the name, this is literally a port of the mod back to forge, the title makes that clear, and the author is different. Anyone with a brain can figure that out. Renaming all of these mods would only make it more confusing to know which is which. 

I have no clue who this dude is or if he's component enough but if he thinks he can port Iris, I fully support him. He's already done three so far. We'll see if he's able to bugfix for the forge ecosystem. I'll be here to test to the best of my ability because I don't think your internal politics should judge who gets to play with which mods.

**Comment by jellysquid3** [comment]
> CaffeineMC seems to be opposed almost entirely because of personal problems with Forge staff.

No, it isn't. I find it really frustrating that people spun it this way. It was just what broke the camel's back.

Simply put: I found it difficult to work on the mods in Forge. After some time it became apparent that Fabric provided a better environment for the specific things my mods were doing. Those technical issues came _long_ before any interpersonal nonsense.  

My issue with "forge ports" were that people took my mod, copied the CurseForge page & kept all our GitHub/Discord links, and often wrecked the stability of the mod all while calling it "Sodium" -- something that happened _multiple_ times. Thankfully, that hasn't happened here!

The Caffeine mods are open source. The FAQ page states that you can port the mods so long as you don't confuse it with the official thing. The license gives you those same rights. I don't believe that's unreasonable.

**Comment by coderbot16** [comment]
> "Damaging your reputation," give me a break. This mod is awesome and Forge players want it. The fact that it is even getting ported means it's a good mod.

It's a good mod *because* I as the lead developer as well as the Iris contributors has poured hundreds to thousands of hours into making it a good mod, *on Fabric*. Iris has better mod compatibility than OptiFine on Fabric because we've spent a lot of time carefully working to ensure that Iris is compatible with what Fabric mods are doing, and because Fabric contains much better interfaces for compatibility between rendering optimization mods and mods adding new content for rendering.

On Forge, where most mods have already included OptiFine compatibility code, and where all existing ports of Sodium have been done in a haphazard way causing many compatibility issues, there's no reason to believe that a haphazard port of Iris + Sodium would actually have better compatibility than OptiFine. And that alone will certainly damage the reputation of Iris, ignoring all other potential issues.

> I don't understand the problem with the name, this is literally a port of the mod back to forge, the title makes that clear, and the author is different. Anyone with a brain can figure that out. Renaming all of these mods would only make it more confusing to know which is which.

You seem to be out of touch with how most Minecraft players actually think. Back when Halogen was named Sodium Reforged, people called it "Sodium" all the time. What evidence do you have that just adding "Reforged" to the name will actually cause people to view the project as something not directly connected to the official Fabric version of the mod?

With this mod too being called Sodium Reforged, this seems to be history repeating itself.

> I'll be here to test to the best of my ability because I don't think your internal politics should judge who gets to play with which mods.

I'd rather that Iris not have a Forge port at all instead of a broken one. Take some time to fully understand what has been written here instead of chalking it up to "internal politics." And, if a Forge port of Iris does exist, it shouldn't have "Iris" in its primary name.
