### ISSUE TITLE
Rendering issue on FTB OceanBlock

### ISSUE THREAD

**Issue by banece** [Someone-Else-Was-Taken/Periodic-Table-Reforged#70]
Currently running FTB OceanBlock and the world is mostly transparent. 

Screenshot: https://i.imgur.com/mkpZZbz.png
Log: https://paste.ee/p/FnXwQ

**Comment by capSAR273** [comment]
Also experiencing the same thing on the latest Magnesium and OceanBlock

**Comment by Popcorncraft** [comment]
Same

**Comment by JeffBittle** [comment]
I was also having this issue, which is a shame because Optifine was giving me noticeable stutters compared to Magnesium.  I noticed that the rendering issue looked fairly similar to the Flywheel compatibility, but Oceanblock doesn't have Flywheel or Create.  However, earlier today this #82 issue was posted initially about Flywheel incompatibility and he found that BetterEnd (Forge) was the cause and that BetterEnd (Reforked) is compatible with Magnesium.

FTB Oceanblock is in fact using BetterEnd (Forge), so I disabled it and installed BetterEnd (Reforked) and sure enough, the rendering issue while using Magnesium is gone.  As BetterEnd (Forge) is no longer being actively maintained, this probably needs to be brought up to the modpack maintainer and suggested that the Forge version be replaced with the Reforked version going forward.

**Comment by banece** [comment]
> I was also having this issue, which is a shame because Optifine was giving me noticeable stutters compared to Magnesium. I noticed that the rendering issue looked fairly similar to the Flywheel incompatibility issue, but Oceanblock doesn't have Flywheel or Create. However, earlier today this #82 issue was posted initially about Flywheel incompatibility and they found that BetterEnd (Forge) was the cause and that BetterEnd (Reforked) is compatible with Magnesium.
> 
> FTB Oceanblock is in fact using BetterEnd (Forge), so I disabled it and installed BetterEnd (Reforked) and sure enough, the rendering issue while using Magnesium is gone. As BetterEnd (Forge) is no longer being actively maintained, this probably needs to be brought up to the modpack maintainer and suggested that the Forge version be replaced with the Reforked version going forward.

Adding to this I tested the Reforked version replacing the reforged and it works. So if anyone is looking for a fix there it is

[Reforked](https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked)
